// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXcAE6XolwPi6rStKHU6gvsYgRgxy29-A',
    appId: '1:189865872427:web:be66503bd29ccbb8406e6e',
    messagingSenderId: '189865872427',
    projectId: 'cfms-bmu-app',
    authDomain: 'cfms-bmu-app.firebaseapp.com',
    storageBucket: 'cfms-bmu-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHzE0D-HnD-N3xog0RLrZx6rxVq1u4ndk',
    appId: '1:189865872427:android:fd585aca22e80a18406e6e',
    messagingSenderId: '189865872427',
    projectId: 'cfms-bmu-app',
    storageBucket: 'cfms-bmu-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHB49xN0WJHGQwwkw91Vbf3CLNZBnsBDs',
    appId: '1:189865872427:ios:fafed89e4dc4e8b3406e6e',
    messagingSenderId: '189865872427',
    projectId: 'cfms-bmu-app',
    storageBucket: 'cfms-bmu-app.firebasestorage.app',
    iosClientId: '189865872427-en5hvt8npshkcco2ul22e1ln45id9g1k.apps.googleusercontent.com',
    iosBundleId: 'com.bmu.cfms',
  );
}
